parser: babel-eslint

plugins:
  - bem-xjst

env:
  browser: true
  node: true
  es6: true
  bem-xjst/bemhtml: true

globals:
  # YModules
  modules: false
  BEMPRIV: true

rules:
  curly: [error, multi-line]

extends: pedant
